### ISSUE TITLE
Re-render the SVG on source change ?

### ISSUE THREAD

**Issue by toverux** [nativescript-community/ui-svg#3]
Hi,

In our application, we use multiple SVG views where we need the source SVG (`[src]`) to change (to indicate disabled states for some buttons, for example, and more).

----------

A little more context:

We tried changing the `[src]` attribute and it didn't work, so we built a workaround, Angular-based solution to re-render the view on source change.

First, we have this structural directive:

```ts
import { Directive, Input, TemplateRef, ViewContainerRef } from '@angular/core';

@Directive({
    selector: '[irRerenderTrigger]'
})
export class RerenderTriggerDirective {
    public constructor(
        private readonly templateRef: TemplateRef<any>,
        private readonly viewContainer: ViewContainerRef) {
    }

    @Input()
    public set irRerenderTrigger(value: unknown) {
        this.reinitialize();
    }

    public reinitialize(): void {
        this.viewContainer.clear();
        this.viewContainer.createEmbeddedView(this.templateRef);
    }
}
```

It is used like this:

```html
<SVGView [src]="svgSource" *irRerenderTrigger="svgSource"></SVGView>
```

Now, if Angular change detection detects that `svgSource` has changed, the directive is called and Angular destroys the `SVGView`, and recreates it from scratch.

This works just fine on Android, however we had a bad surprise on iOS, the thing crashes with this error on render:

```
NativeScript encountered a fatal error: Uncaught TypeError: Cannot read property 'viewRect' of null
  at onMeasure(file: redacted/node_modules/@nativescript-community/ui-svg/index.js:213:0)
  at measure(file: redacted/node_modules/@nativescript/core/ui/core/view/index.js:50:0)
```

The line in question:

```js
const image = this.nativeViewProtected.renderer.viewRect;
```

----------

So, we'd really like:

 - that the library is able to support re-rendering an SVG natively ;
 - or in the short term, a little guidance on how to avoid this error, or some kind of bugfix.

In any case, thanks for your work that allowed us to have a crisp render for our illustrations and buttons!

Thanks in advance!

**Comment by farfromrefug** [comment]
@toverux does changing the src property on android updates the view correctly? (it should)

**Comment by toverux** [comment]
No, unfortunately it never worked. That's why we built this workaround, on Android first, before testing it on iOS where there are other problems.

We are declaring `<SVGView>` like this:

```ts
import { SVGView } from '@nativescript-community/ui-svg';

registerElement('SVGView', () => SVGView);
```

Then, we directly set `SVGView#src` to a new value (reading it afterwards shows that it's been set) but the SVG is never rasterized again.

(By the way, types seem off too since the types of the class `SVGView` doesn't have [src] attribute, but it has one - among many others - at runtime, we have to use the `SVG` class for typing instead. Edit: reading the source code a little bit more confuses me even more, I don't understand from where the SVGView class gets all its properties at runtime :sweat_smile: Also, why is the strecth property code commented out on Android ? I already noticed that it didn't work on this platform).

**Comment by toverux** [comment]
I did another test where I change the source but using a malformed SVG string:

```ts
svgView.src = 'not a svg';
```

Now I get this error:

```
JS: ERROR Error: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT not an svg@1:11 in java.io.InputStreamReader@8ead83f)
```

So at least we know that the new SVG is at least parsed, but never rendered.

**Comment by farfromrefug** [comment]
@toverux all should be fixed in 0.0.6. Please let me know

**Comment by toverux** [comment]
Thanks @farfromrefug, I can confirm that everything works as expected on Android!

On iOS we still have `Uncaught TypeError: Cannot read property 'viewRect' of null` on some SVGs (please note that we removed our `*irRerenderTrigger` workaround thanks to the fix, so this happens with the library on its own). We lack time to do more thorough testing on iOS right now to understand why this happens in some cases, but I could get back to you in a few days if you have no clue about this either.

**Comment by farfromrefug** [comment]
@toverux i tested and the IOS worked fine here (you can test the demo app in this repo). So yes more details would help, for now cant do much more

**Comment by fklingler** [comment]
Hi @farfromrefug, I'm working with @toverux.

I searched a bit more and the problem happens when the `src` property is not set (or not set immediately, in our case). The app still calls `onMeasure()` but the renderer is not initialized.

I suppose we could protect this by doing something like that at the beginning of `onMeasure`

```
        if (!this.nativeViewProtected.renderer) {
            super.onMeasure(widthMeasureSpec, heightMeasureSpec);
            return;
        }
```

It works for me but I don't know if there is any unwanted side effect with such a change.
I can submit a PR if you're OK with this change.

**Comment by farfromrefug** [comment]
@fklingler thanks now i understand! fixed in 0.0.7

**Comment by fklingler** [comment]
Thanks, it's working now!

**Comment by toverux** [comment]
Thanks for your help @farfromrefug!
