### ISSUE TITLE
Doesn't show SVG with any of the 3 methods

### ISSUE THREAD

**Issue by butaminas** [nativescript-community/ui-svg#4]
**Using:**
- iOS / emulator and device / iPhone 7+ or iPhone 12 / iOS 14.4

**tns --version**
nativescript has 7.2.0
@nativescript/core has 7.3.0
@nativescript/ios has 7.2.0
@nativescript/android has 7.0.1

I don't use nothing special in my app, in fact, I've made it load a blank component without any additional plugins just to see if it would make any difference but it didn't.

The result is that I don't see any SVG image. I don't get any errors it is just blank where an SVG image should be.

**Comment by farfromrefug** [comment]
@butaminas maybe it would be best to share a sample code, don't you think ? ;)

**Comment by butaminas** [comment]
> @butaminas maybe it would be best to share a sample code, don't you think ? ;)

OK. Fair enough.

`ns create HelloWorld --template @nativescript/template-blank-vue`  
Doesn't work with the default blank template.  
  
  
Also adding [a link to the code](https://we.tl/t-c7jHGtW3RS) but it is just the blank template with this plugin on top.

**Comment by butaminas** [comment]
@farfromrefug I think I figured out where the issue is.  
I have my SVG at `/app/images/image.svg` and when I try to link it in the `<SVGView src='~/images/image.svg' />` tag it doesn't work. But if I change the structure like in the docs and have the image in `/app/assets/svgs/image/svg/image.svg` and then link it like so `<SVGView src='~/assets/svgs/image.svg' />` then it works.

Is there any particular reason why it has to be under `assets/svgs` if not, is there any way to change the directory?

**Comment by farfromrefug** [comment]
you issue is not with this plugin but with your path. must be ~/assets/...

**Comment by NavruzbekNoraliev** [comment]
how can I use this library to get SVG from a URL?

i want something like this: 
`<SVGView height="30%" src="url"><SVGView>`

**Comment by dancosta-fed** [comment]
> 

Hey.. were you able to figure it out?

**Comment by dancosta-fed** [comment]
> how can I use this library to get SVG from a URL?
> 
> i want something like this: `<SVGView height="30%" src="url"><SVGView>`

Hey.. were you able to figure it out?
