### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by msosnowski-dev** [nativescript-community/ui-svg#7]
Sory but its not work - blank page

app.js
import Vue from 'nativescript-vue'
import CanvasSVG from '@nativescript-community/ui-svg/vue';
Vue.use(CanvasSVG);
import Home from './components/Home'

new Vue({
  render: (h) => h('frame', [h(Home)]),
}).$start()

Home.vue
<template>
    <Page>
        <ActionBar>
            <Label text="Home"/>
        </ActionBar>

            <CanvasSVG>
                <CSVG horizontalAlignment="left" src="~/images/tiger.svg" height="100%" stretch="aspectFit" />
            </CanvasSVG>
    </Page>
</template>

package.json
{
  "name": "@nativescript/template-blank-vue",
  "main": "app/app.js",
  "displayName": "Blank",
  "version": "8.0.4",
  "description": "NativeScript Application",
  "author": "NativeScript Team <oss@nativescript.org>",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "homepage": "https://github.com/NativeScript/nativescript-app-templates",
  "bugs": {
    "url": "https://github.com/NativeScript/NativeScript/issues"
  },
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "app",
    "App_Resources",
    "hooks",
    "tools",
    "!tools/assets",
    ".editorconfig",
    "jsconfig.json"
  ],
  "keywords": [
    "nstudio",
    "nativescript",
    "mobile",
    "{N}",
    "tns",
    "vue",
    "nativescript-vue",
    "template",
    "master-detail",
    "detail",
    "category-general"
  ],
  "dependencies": {
    "@nativescript-community/ui-svg": "^0.0.8",
    "@nativescript/core": "~8.0.0",
    "@nativescript/theme": "~3.0.1",
    "nativescript-vue": "~2.9.0"
  },
  "devDependencies": {
    "@nativescript/android": "8.0.0",
    "@nativescript/webpack": "beta",
    "nativescript-vue-template-compiler": "~2.9.0",
    "sass": "^1.32.8"
  },
  "private": "true",
  "readme": "NativeScript Application"

**Comment by farfromrefug** [comment]
@maniutek08 seeing how you use it you should use `SVGView` instead of `CanvasSVG`

**Comment by msosnowski-dev** [comment]
If i use SVGView instead CanvasSVG, I get error : 
`System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onCreateView failed
System.err: Error: java.io.FileNotFoundException: /data/data/org.nativescript.imageSVG/files/app/images/tiger.svg: open failed: ENOENT (No such file or directory)
`
I have no idea but the tiger.svg file is in the 'app/images' folder..

**Comment by farfromrefug** [comment]
@maniutek08 this is your issue. You need to investigate why it cant find the file. Cant really help there

**Comment by msosnowski-dev** [comment]
Okay, but when I use a regular Image element that points to a file in the same folder it displays this. This is not a file location problem

**Comment by farfromrefug** [comment]
@maniutek08 actually i think it is. I think your webpack config does not copy the svg file!

**Comment by msosnowski-dev** [comment]
I am a newbie in nativescript, I  was creating a clean nativescript project in vue I added this plugin, imported components. Is there anything else I should do? Nothing is written in the installation manual ...

**Comment by farfromrefug** [comment]
@maniutek08 put your svg into the assets folder. That folder is copied without any filter rule. Then use `assets` in the path like shown in the demo code.

**Comment by msosnowski-dev** [comment]
@farfromrefug it works! sorry for the confusion but I had no idea it must be an "assets" folder. Can I still have a novice question why it has to be an "assets" folder and not some own named? .. Probably I do not know something again, which for all of them is probably obvious

**Comment by farfromrefug** [comment]
@maniutek08 it is because their must be a webpack rule on how to copy stuff. the rule for `assets` already exists. For images like png/jpg/bmp there is a rule to copy it whatever the path.
