### ISSUE TITLE
Build error: export 'init' was not found in '@nativescript-community/text'

### ISSUE THREAD

**Issue by toverux** [nativescript-community/ui-svg#8]
Hi,

After migrating to NativeScript 8 we encounter a build error in ui-svg:

```
WARNING in ./node_modules/@nativescript-community/ui-svg/index.common.js 5:0-4
export 'init' (imported as 'init') was not found in '@nativescript-community/text' (possible exports: cssProperty, verticalTextAlignmentConverter, verticalTextAlignmentProperty)
 @ ./node_modules/@nativescript-community/ui-svg/index.android.js 3:0-105 4:0-43 4:0-43 49:25-32 175:86-104 324:29-40 335:5-26
 @ ./projects/app.mobile/app/shared/directives/svg.directive.ts 2:0-57 5:33-40
 @ ./projects/app.mobile/app/shared/shared.module.ts 35:0-50 68:105-121
 @ ./projects/app.mobile/app/app.module.ts 22:0-54 28:0-45 108:2-22
 @ ./projects/app.mobile/main.ts 6:0-45 10:51-60
```

In fact init() exists, but only in the platform-specific index files of `@nativescript-community/ui-svg`.
It only seems to resolve the standard index `index.js` of that library, where's there no init of course.

But in the require stack you may see that for ui-svg at least it works, while in our app we import just as `@nativescript-community/ui-svg`, it's resolved as `@nativescript-community/ui-svg/index.android.js` which is good.

Of course at runtime it will cause an error because init is undefined:

```
TypeError: (0 , _nativescript_community_text__WEBPACK_IMPORTED_MODULE_0__.init) is not a function
```

I don't know why it doesn't work between dependencies and any help would be appreciated.

 - nativescript@8.3.2
 - @nativescript-community/ui-svg@0.1.0

**Comment by farfromrefug** [comment]
@toverux you need to check your plugins versions and stuff. I can confirm init method exists https://github.com/nativescript-community/text/blob/master/src/index.android.ts#L124

**Comment by toverux** [comment]
Hi, thanks for answering.
Yes indeed the init function exists, for sure. The actual problem is that Webpack resolves the platform-agnostic file like it would normally do (if NS didn't override how extensions are resolved). Where's there's *no* init because it's *not* index.android.js that's resolved.
It seems like a Webpack problem after all, ui-svg <-> text linking works on another project but we can't pinpoint any configuration/versions difference.
Will continue to investigate.

**Comment by toverux** [comment]
It was indeed a Webpack configuration problem, making .js files taking precedence over .{platform}.js files in the cases where the .js file existed (like here).
